Leçons de coaching agile
les-traducteurs-agiles/les-traducteurs-agiles.github.io pull request #82
Opened 2020-11-08 12:23 UTC by Moosh-be

- [ ] * Leçon 01 : [Signalez que vous n'avez aucune autorité](http://www.les-traducteurs-agiles.org/2015/02/17/signalez-que-vous-n-avez-aucune-autorite-lecon-1.html)
- [ ] * Leçon 02 : [Votre posture est votre message](http://www.les-traducteurs-agiles.org/2015/02/19/votre-posture-est-votre-message-lecon-2)
- [ ] * Leçon 03 : [Utilisez votre corps lorsque vous facilitez](http://www.les-traducteurs-agiles.org/2015/02/13/utilisez-votre-corps-lorsque-vous-facilitez-lecon-3)
- [ ] * Leçon 04 : [L'auto-organisation est de l'auto-gestion](http://www.les-traducteurs-agiles.org/2015/02/19/l-auto-organisation-est-de-l-auto-gestion-lecon-4.html)
- [ ] * Leçon 05 : [L'autogestion, c'est l'autorité distribuée par consentement](http://www.les-traducteurs-agiles.org/2015/02/18/l-autogestion-c-est-l-autorite-distribuee-par-consentement-lecon-5.html)
- [ ] * Leçon 06 : [Votre style autoritaire tue l'auto-organisation](http://www.les-traducteurs-agiles.org/2015/02/19/votre-style-autoritaire-tue-l-auto-organisation-lecon-6.html)
- [ ] * Leçon 07 : [Invitez à la facilitation](http://www.les-traducteurs-agiles.org/2015/02/20/invitez-a-la-facilitation-lecon-7.html)
- [ ] * Leçon 08 : [Les pratiques changent, pas les principes](http://www.les-traducteurs-agiles.org/2015/02/22/les-pratiques-changent-pas-les-principes-lecon-8.html)
- [ ] * Leçon 09 : [Commencez dans le Forum Ouvert](http://www.les-traducteurs-agiles.org/2015/02/25/commencez-dans-le-forum-ouvert-lecon-9.html)
- [ ] * Leçon 10 : [Le Forum Ouvert raconte une histoire](http://www.les-traducteurs-agiles.org/2015/02/26/le-forum-ouvert-raconte-une-histoire-lecon-10.html)
- [ ] * Leçon 11 : [Encouragez les managers à encourager l'expérimentation](http://www.les-traducteurs-agiles.org/2015/03/21/encouragez-les-managers-a-encourager-l-experimentation-lecon-11.html)
- [ ] * Leçon 12 : [Je veux écrire l'histoire](http://www.les-traducteurs-agiles.org/2015/03/20/je-veux-ecrire-l-histoire-lecon-12.html) (et être DANS l'histoire...)
- [ ] * Leçon 13 : [Lorsqu'ils disent non, réduisez la demande de moitié](http://www.les-traducteurs-agiles.org/2015/03/29/lorsqu-ils-disent-non-reduisez-la-demande-de-moitie-lecon-13.html)
- [ ] * Leçon 14 : [L'engagement est tout](http://www.les-traducteurs-agiles.org/2017/05/03/l-engagement-est-tout-lecon-14.html)
- [ ] * Leçon 15 : [Les véritables leaders y vont en premier](http://www.les-traducteurs-agiles.org/2016/01/26/etape-1-les-leaders-y-vont-en-premier-lecon-15.html)
- [ ] * Leçon 16 : [Aidez l'équipe à identifier ses valeurs fondamentales dès que possible](http://www.les-traducteurs-agiles.org/2016/12/28/alignez-les-equipes-sur-leurs-valeurs-fondamentales-des-que-possible-lecon-16.html)
- [ ] * Leçon 17 : [POUSSER l'Agile provoque des "Transe-formations"](http://www.les-traducteurs-agiles.org/2017/06/16/pousser-l-agile-provoque-des-transe-formations-lecon-17.html)
- [ ] * Leçon 18 : [Les définitions sont des accords](http://www.les-traducteurs-agiles.org/2017/06/17/les-definitions-sont-des-accords-lecon-18.html)
- [ ] * Leçon 19 : [Agile est un jeu. Mettez-vous d'accord sur les règles](http://www.les-traducteurs-agiles.org/2017/07/20/agile-est-un-jeu-mettez-vous-d-accord-sur-les-regles-lecon-19.html)
- [ ] * Leçon 20 : [Seul celui qui est engagé peut s'auto-organiser](http://www.les-traducteurs-agiles.org/2017/07/20/seul-celui-qui-est-engage-peut-s-auto-organiser-lecon-20.html)
- [ ] * Leçon 21 : [Finir par un forum ouvert](http://www.les-traducteurs-agiles.org/2017/07/21/finir-par-un-forum-ouvert-lecon-21.html)
- [ ] * Leçon 22 : [Obtenez-le par écrit](http://www.les-traducteurs-agiles.org/2017/12/23/obtenez-le-par-ecrit-lecon-22.html)

2020-11-10 20:42 UTC, nmereaux requested changes
Hello Christophe, voici quelques éléments à modifier stp.
Merci beaucoup

2020-11-10 20:42 UTC, nmereaux commented on _posts/2015-02-22-les-pratiques-changent-pas-les-principes-lecon-8.markdown
> +Vous devez démarrer avec le Manifeste Agile si vous voulez avoir une chance de mener à bien votre accompagnement de "transfoœuvrermation Agile".
J'avoue ne pas comprendre ta proposition Christophe … !^_^

2020-11-10 20:42 UTC, nmereaux commented on _posts/2016-01-26-etape-1-les-leaders-y-vont-en-premier-lecon-15.markdown
> +Si vous, le soi-disant "coach Agile", ne pouvez aider les leaders officiels à aller dans cette direction, l'adoption de l'Agilité et de la prétendue 'transformation" est probablement paralysée.
Merci pour la proposition de "prétendue", toutefois la répétition de soi-disant est faite exprès ;)

2020-11-10 20:42 UTC, nmereaux commented on _posts/2017-07-20-agile-est-un-jeu-mettez-vous-d-accord-sur-les-regles-lecon-19.markdown
> +1. Il y a désormais un sentiment d'appartenance à une communauté - tout le monde partage l'accord. L'accord décrit les RÈGLES DU JEU. Que tous s's’apprêtent à jouer.
OK pour "s'apprêtent" au pluriel - avec un seul " s' " par contre  :)

2020-11-11 19:33 UTC, Moosh-be commented on _posts/2015-02-22-les-pratiques-changent-pas-les-principes-lecon-8.markdown
> +Vous devez démarrer avec le Manifeste Agile si vous voulez avoir une chance de mener à bien votre accompagnement de "transfoœuvrermation Agile".
oh purée,  à vouloir aller trop vite je fais pire que bien.

2020-11-11 19:34 UTC, Moosh-be commented on _posts/2016-01-26-etape-1-les-leaders-y-vont-en-premier-lecon-15.markdown
> +Si vous, le soi-disant "coach Agile", ne pouvez aider les leaders officiels à aller dans cette direction, l'adoption de l'Agilité et de la prétendue 'transformation" est probablement paralysée.
Donc autant garder l'entorse pour insister sur l'écho

2020-11-11 20:47 UTC, Moosh-be commented on _posts/2017-07-20-agile-est-un-jeu-mettez-vous-d-accord-sur-les-regles-lecon-19.markdown
> +1. Il y a désormais un sentiment d'appartenance à une communauté - tout le monde partage l'accord. L'accord décrit les RÈGLES DU JEU. Que tous s's’apprêtent à jouer.
done

2020-11-11 20:48 UTC, Moosh-be commented on _posts/2016-01-26-etape-1-les-leaders-y-vont-en-premier-lecon-15.markdown
> +Si vous, le soi-disant "coach Agile", ne pouvez aider les leaders officiels à aller dans cette direction, l'adoption de l'Agilité et de la prétendue 'transformation" est probablement paralysée.
revenu à soi-disant mais invariable quand même

2020-11-17 20:35 UTC, merged