L'estimation à l'origine des échecs des projets informatiques
les-traducteurs-agiles/les-traducteurs-agiles.github.io pull request #83
Opened 2020-11-18 20:55 UTC by Moosh-be

coquilles

2020-11-28 19:52 UTC, nmereaux requested changes

2020-11-28 19:52 UTC, nmereaux commented on _posts/2015-09-20-estimation-en-heures.markdown
> +Du gâchis, voilà ce qu'il se passe. Faire la décomposition des tâches est souvent inefficace et inefficient. Ne soyez pas cette personne. Travaillez à la place avec des stories complètes. (voire plus
Hello, c'est bien voir sans e ;)

2020-11-28 21:00 UTC, Moosh-be commented on _posts/2015-09-20-estimation-en-heures.markdown
> +Du gâchis, voilà ce qu'il se passe. Faire la décomposition des tâches est souvent inefficace et inefficient. Ne soyez pas cette personne. Travaillez à la place avec des stories complètes. (voire plus
Sûr ? 

```
"Voir" est un verbe tandis que "voire" est une conjonction.
Dans une phrase, lorsque vous hésitez sur l'un ou l'autre, retenez simplement que :

Si vous pouvez remplacer, dans votre phrase, le verbe "voir" 
par n'importe quel autre verbe et que votre phrase est toujours correcte 
alors vous ne mettez pas de "e" à voir.
 
Si vous ne pouvez pas le remplacer par un verbe, 
mais qu'à la place vous pouvez le remplacer  par, "et même", alors écrivez "voire".
```


"marcher plus loin" => Voir

"Et même plus loin" => Voire

2020-11-29 19:16 UTC, nmereaux commented on _posts/2015-09-20-estimation-en-heures.markdown
> +Du gâchis, voilà ce qu'il se passe. Faire la décomposition des tâches est souvent inefficace et inefficient. Ne soyez pas cette personne. Travaillez à la place avec des stories complètes. (voire plus
Oui m'sieur :) 
J'aurais dû être plus explicite dans mon précédent message.
Le sens de la phrase "voir plus loin" dans le texte est là pour indiquer au lecteur que le sujet de "Travaillez à la place avec des stories complètes" est traité plus loin.
Est-ce que cela te paraît plus clair ? Si cela te paraît mieux, il est possible de mettre "cf. plus loin" à la place.

2020-11-29 20:20 UTC, Moosh-be commented on _posts/2015-09-20-estimation-en-heures.markdown
> +Du gâchis, voilà ce qu'il se passe. Faire la décomposition des tâches est souvent inefficace et inefficient. Ne soyez pas cette personne. Travaillez à la place avec des stories complètes. (voire plus
ahahah non, Tilt j'ai compris

2020-11-30 19:41 UTC, nmereaux commented on _posts/2015-09-20-estimation-en-heures.markdown
> +Du gâchis, voilà ce qu'il se passe. Faire la décomposition des tâches est souvent inefficace et inefficient. Ne soyez pas cette personne. Travaillez à la place avec des stories complètes. (voire plus
:)

2020-12-04 20:10 UTC, merged